### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by FunnyUser** [Calico90/codeigniter-version-tester#2]
I'm newbie in php classes, just wrote few scripts for administration. 

Could you please navigate me how to run version check on custom site?

Thank you in advance.

**Comment by Calico90** [comment]
Can you specify your question more. What did you try and worked or didn't work?

**Comment by FunnyUser** [comment]
I have external website running codeigniter, and want to check it's version. And I can't figure out the way to use your tool.

**Comment by Calico90** [comment]
If you are running the site yourself you should check the `/system/core/CodeIgniter.php` file.

https://github.com/bcit-ci/CodeIgniter/blob/develop/system/core/CodeIgniter.php#L58

CI_VERSION shows the version you are running. If you want to run this check externally I suggest checking out https://github.com/Calico90/codeigniter-version-tester/blob/master/src/index.php and changing the URL. Note that this project is still in development.
